---
- name: Install remote facts
  hosts: undercloud
  become: yes
  become_method: sudo
  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: custom.fact
  tasks:
    - name: collect rhos version and include relevant auth file
      shell: |
        rhos-release -L | sed -n 2p | tr -d [:space:]
      register: rhos_version
    - name: Create the remote directory
      file:
        state: directory
        recurse: yes
        path: "{{ remote_dir }}"
    - name: Install the new facts
      template:
        src: custom.fact.j2
        dest: "{{ remote_dir }}/custom.fact"