- include: auth.yml
- hosts: undercloud
  vars:
    ansible_python_interpreter: /var/tmp/venv_shade/bin/python
  gather_facts: no
  any_errors_fatal: true
  tasks:
    - include_vars:
        file: images.yml
        name: images
    - name: download cirros image
      get_url:
        url: "{{ images.cirros_url }}"
        dest: /tmp/cirros-0.3.4-x86_64-disk.img
    - name: download fedora image
      get_url:
        url: "{{ images.fedora_url }}"
        dest: /tmp/Fedora-Atomic-25-20161207.0.x86_64.qcow2
    - name: upload cirros image
      os_image:
        auth: "{{ os_creds }}"
        name: heat_cirros_image
        container_format: bare
        is_public: yes
        disk_format: qcow2
        filename: /tmp/cirros-0.3.4-x86_64-disk.img
        state: present
    - name: upload fedora image
      os_image:
        auth: "{{ os_creds }}"
        name: heat_fedora_image
        container_format: bare
        is_public: yes
        disk_format: qcow2
        filename: /tmp/Fedora-Atomic-25-20161207.0.x86_64.qcow2
        state: present
    - name: Configure heat network on overcloud
      os_network:
        cloud: overcloud
        name: heat-net
    - name: Configure heat subnet on heat network
      os_subnet:
        network_name: heat-net
        name: heat-subnet
        cidr: 10.0.5.0/24
        auth: "{{ os_creds }}"
    - name: Configure heat router
      os_router:
        name: router1
        auth: "{{ os_creds }}"
        interfaces: 
          - heat-subnet
    - name: Configure heat keypair 
      os_keypair:
        name: heat_keypair
        auth: "{{ os_creds }}"
    - name: Configure heat m1.small flavor 
      os_nova_flavor:
        ram: 2048
        disk: 7
        vcpus: 1
        name: m1.small
        auth: "{{ os_creds }}"
    - name: create m1.tiny flavor
      os_nova_flavor:
        ram:  512
        disk: 7
        vcpus: 1
        name: m1.tiny
        auth: "{{ os_creds }}"
    - name: Modify testr regex to fix API failures
      ini_file:
        path: ./tempest-dir/.testr.conf
        section: DEFAULT
        option: group_regex
        value: heat_integrationtests\\.api\\.test_heat_api(?:\\.|_)([^_]+)
        mode: 0600
        backup: yes
        
