- include: auth.yml
- include: auth_demo.yml
- hosts: undercloud
  vars:
    ansible_python_interpreter: "/home/stack/ir_venv/bin/python"
  gather_facts: no
  any_errors_fatal: true
  tasks:
    - include_vars:
        file: images.yml
        name: images
    - name: download cirros image
      get_url:
        url: "{{ images.cirros_url }}"
        dest: /tmp/cirros-0.3.4-x86_64-disk.img
    - name: download fedora image
      get_url:
        url: "{{ images.fedora_url }}"
        dest: /tmp/Fedora-Atomic-25-20161207.0.x86_64.qcow2
    - name: upload cirros image
      os_image:
        auth: "{{ os_creds }}"
        id: 13e4c9b6-b73b-4770-9067-bfe2c107c49c # a workaround until ansible 2.4.1 will be released https://github.com/ansible/ansible/issues/29145
        name: heat_cirros_image
        container_format: bare
        is_public: yes
        disk_format: qcow2
        filename: /tmp/cirros-0.3.4-x86_64-disk.img
        state: present
    - name: upload fedora image
      os_image:
        auth: "{{ os_creds }}"
        id: 7f862026-9988-456c-97f7-9a16e93189cd # a workaround until ansible 2.4.1 will be released https://github.com/ansible/ansible/issues/29145
        name: heat_fedora_image
        container_format: bare
        is_public: yes
        disk_format: qcow2
        filename: /tmp/Fedora-Atomic-25-20161207.0.x86_64.qcow2
        state: present
    - name: Configure heat network on overcloud
      os_network:
        name: heat-net
        auth: "{{ os_demo }}"
    - name: Configure heat subnet on heat network
      os_subnet:
        network_name: heat-net
        name: heat-subnet
        cidr: 10.0.5.0/24
        auth: "{{ os_demo }}"
    - name: Configure heat router
      os_router:
        name: router1
        auth: "{{ os_demo }}"
        interfaces:
          - heat-subnet
    - name: Configure heat keypair
      os_keypair:
        name: heat_keypair
        auth: "{{ os_demo }}"
    - name: Configure heat m1.small flavor
      os_nova_flavor:
        ram: 2048
        disk: 7
        vcpus: 1
        name: m1.small
        auth: "{{ os_creds }}"
    - name: create m1.tiny flavor
      os_nova_flavor:
        ram:  512
        disk: 7
        vcpus: 1
        name: m1.tiny
        auth: "{{ os_creds }}"
    - name: add swift role to demo user
      os_user_role:
        auth: "{{ os_creds }}"
        user: demo
        role: swiftoperator
        project: demo
      ignore_errors: yes

