- name: modify conf file
  ini_file:
    path: "{{ integrationtests_path }}"
    section: DEFAULT
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - {option: "username", value: "demo"}
    - {option: "password", value: "secrete"}
    - {option: "auth_url", value: "{{ osp_auth.stdout }}"}
    - {option: "tenant_name", value: "demo"}
    - {option: "user_domain_name", value: "Default"}
    - {option: "project_domain_name", value: "Default"}
    - {option: "region", value: "regionOne"}
    - {option: "auth.version", value: "2"}
    - {option: "admin_username", value: "admin"}
    - {option: "admin_password", value: "{{ osp_password.stdout }}"}
    - {option: "keypair_name", value: "heat_keypair"}
    - {option: 'image_ref', value: 'heat_fedora_image'}
    - {option: 'minimal_image_ref', value: 'heat_cirros_image'}
    - {option: "instance_type", value: "m1.small"}
    - {option: "minimal_instance_type", value: "m1.tiny"}
    - {option: "image_ssh_user", value: "root"}

